### ISSUE TITLE
Handling playlists

### ISSUE THREAD

**Issue by strooooke** [lambdasoup/watchlater#12]
The URI schema forces us at least in some occasions (e.g. http://www.youtube.com/attribution_link?u=/playlist%3Flist%3DPL0INsTTU1k2UO-2-AwomFmAs4nuZU9ht3%26feature%3Dem-share_playlist_user ) to accept intents for adding playlists.

Those could be handled by adding all videos in the playlist to watchlater, or by saving the playlist for the user (arguably outside the watchlater scope and can easily be done by just using the Youtube app for the intent and pressing the + icon there).

**Comment by strooooke** [comment]
Saving the playlist, as in the web interface, cannot currently be done with the API (see https://code.google.com/p/gdata-issues/issues/detail?id=6610 ).

#14 permits this with some additional user interaction.

An "Add all" button to add all the items in the playlist to watchlater would be potentially useful, though expensive in terms of requests.

**Comment by strooooke** [comment]
"Add all" functionality would require:
* 1 request to fetch name and itemcount of the playlist
* a variable number of request to list the playlistItems in the playlist (can only do batches, with a maxSize of 50)
* 1 request/playlistItem to insert it into the WL playlist

**Comment by maxhille** [comment]
not possible anymore since the list is not readable
