### ISSUE TITLE
Perform completely correctly on orientation change: no duplicate requests etc.

### ISSUE THREAD

**Issue by strooooke** [lambdasoup/watchlater#28]
Time for a service!

**Comment by strooooke** [comment]
Do all work in bound and started service. If correct activity is still bound, deliver result to activity on completion; if not, deliver result through notification (that can relaunch the result screen activity as action, via intent extras).

Best results considering history are had by implementing #35 first.

**Comment by maxhille** [comment]
obsoleted by v2
