### ISSUE TITLE
Choosing 'default' youtube channel not working anymore - modify help text

### ISSUE THREAD

**Issue by strooooke** [lambdasoup/watchlater#33]

**Comment by maxhille** [comment]
As far as we know, the default channel setting should work (as it is an officially suggested workaround[1])
I reported a bug to Google[2]

[1] https://support.google.com/youtube/answer/3046478
[2] https://code.google.com/p/gdata-issues/issues/detail?id=8128

**Comment by maxhille** [comment]
I think it has been fixed. Noone knows for sure but I had this problem and it went away. Closing this until other reports come in again.
