### ISSUE TITLE
Launcher Activity as watchlater playlist manager

### ISSUE THREAD

**Issue by strooooke** [lambdasoup/watchlater#34]
Wished for improvements over youtube app:
- reversible sort order
- moving position of playlistitems in playlist (possibly only doable with loads of requests)

**Comment by maxhille** [comment]
Since it will no longer be possible to read the list items soon, this enhancement is void. While there could be use for a general playlist manager or maybe the move to an App-specific "Watch Later" playlist, I would say we close this.
