### ISSUE TITLE
Redesign main activity to show state, not process

### ISSUE THREAD

**Issue by strooooke** [lambdasoup/watchlater#35]
Main activity should still be a dialog. On create, fetch status of video with regards to watchlater playlist of chosen channel/account:
- account choice first (if necessary)
- fetch video description (possibly in parallel to the other requests)
- fetch playlist id
- fetch info whether in playlist or not (playlistItems.list request with playlistId and videoId -> 0 or 1 result. Comes with title and description, but of course only if the video is actually in the playlist)
- show video info and two buttons: "open with youtube" and, if video not in playlist, "add to watch later". (possibly: "remove from watch later" if in playlist).
- after add successfull, show info screen again, with new state
- or error state with try again as usual.

**Comment by maxhille** [comment]
obsoleted by v2
