### ISSUE TITLE
YouTube API shut down error

### ISSUE THREAD

**Issue by ElmorenohWTF** [lambdasoup/watchlater#53]
I'm having this message for like 2 days: could not add video: an error ocurred (Other)![Screenshot_20210211-000657.png](https://user-images.githubusercontent.com/62709646/107585026-c4f1a200-6bfd-11eb-8898-078f132f609d.png)

**Comment by maxhille** [comment]
Thanks for the report. Looks like YouTube finally shut down the API method to insert videos into the Watch Later playlist. Workaround will be to use a regular ("user") playlist instead, I'll try to update the app as soon as possible.

**Comment by maxhille** [comment]
We will fast track a small update with  https://github.com/lambdasoup/watchlater/commit/c2f4f33377facccd680ec80b55caa507c093ed02 which at least gives a more detailed error message until a proper update is done.

**Comment by ElmorenohWTF** [comment]
I see, youtube eliminating things because yes, as always. Thank you for your amazing work, I look forward to the next update to continue using this cool app that saves me so much time.

**Comment by maxhille** [comment]
Version 2.3.0 which uses regular user playlists is now available in the beta channel. I'll keep this issue open for a while to track possible problems. The implementation is a bit rough and simple so there might be issues UX wise, too.

Please try and give feedback!

**Comment by GeoffreyPlitt** [comment]
@maxhille Cool! I tried the new build. Getting a crash when I go to choose a playlist. Twice now. On stock Samsung Galaxy S10e. Let me know if you want me to send more info.

**Comment by maxhille** [comment]
I got the stack trace - I encountered the crash myself. I'll look into fixing it now. What worked for me as a workaround was to reselect the Google account.

**Comment by maxhille** [comment]
A patched version (2.3.1) is not in the beta channel.

**Comment by GeoffreyPlitt** [comment]
Worked for me. Everything's great now. Thanks!

**Comment by skoshy** [comment]
In the beta version, I'm still having trouble seeing all of my playlists. It looks like only a max of 50 playlists are populated. Could the call be made to include all playlists?

**Comment by maxhille** [comment]
I will close this issue since the version has been rolled out for everyone (100% production) already.

@skoshy I created a new issue for the max playlists (https://github.com/lambdasoup/watchlater/issues/55)

**Comment by GeoffreyPlitt** [comment]
Thanks!
